version: 2
jobs:
  laravel:
    working_directory: /app
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: login docker
          command: echo $DOCKER_PASS| docker login -u $DOCKER_USER --password-stdin
      - run:
          name: build image
          command: docker build -t $DOCKER_IMAGE:laravel .
      - run:
          name: push image
          command: docker push $DOCKER_IMAGE:laravel
    filtered:
      branches:
        only: 
          laravel

  yii:
    working_directory: /app
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: login docker
          command: echo $DOCKER_PASS| docker login -u $DOCKER_USER --password-stdin
      - run:
          name: build image
          command: docker build -t $DOCKER_IMAGE:yii .
      - run:
          name: push image
          command: docker push $DOCKER_IMAGE:yii
    filtered:
      branches:
        only:
          yii


workflows:
  version: 2
  build:
    jobs:
      - laravel
      - yii


